name: patient_monitor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=24.3.1
  - numpy=1.24.4
  - pandas=2.0.3
  - opencv=4.6.0
  - pip:
    - fastapi==0.110.0
    - uvicorn[standard]==0.27.1
    - websockets==12.0
    - bleak==0.22.3
    - python-multipart==0.0.9
    - pydantic==2.6.1
    - asyncio==3.4.3
    - aiofiles==23.2.1
    - python-jose[cryptography]==3.3.0
    - pytest==8.0.0
    - pytest-asyncio==0.23.5
